# -*- coding: utf-8 -*-
"""homework_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F_rkA9TFdvrM1_tOhSGi5xLsRWyirtIt
"""

import pandas as pd

import numpy as np

import random

lst = ['robot'] * 10

lst += ['human'] * 10

random.shuffle(lst)

data = pd.DataFrame({'whoAmI': lst})

print(data)

data['tmp'] = 1

data.set_index([data.index, 'whoAmI'], inplace=True)

data = data.unstack(level=-1, fill_value = 0).astype(int)

data.columns = data.columns.droplevel()

data.columns.name = None

print(data)